version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/packages/color"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "01:00"
      timezone: "Asia/Shanghai"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/primitives/utils"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
      timezone: "Asia/Shanghai"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/primitives/type-utils"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Asia/Shanghai"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/primitives/filed-form"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Shanghai"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/packages/tailwind-plugin"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "Asia/Shanghai"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/packages/ui"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Asia/Shanghai"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/playground"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Asia/Shanghai"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/packages/next-docs-plugin"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Asia/Shanghai"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    labels:
      - "dependencies"
